### ISSUE TITLE
Discrepancy with 'of'

### ISSUE THREAD

**Issue by obromios** [thenickcox/syllabize#9] opened 2015-01-01 06:50 UTC
Thank you for developing this gem, I do appreciate it.

When a word with silent e at the end is followed by 'of', there seems to be an extra syllable count, e.g.
    'Anne of'.count_syllables
    => 3
   'Anne'.count_syllables
   => 1
   'of'.count_syllables
   => 1

But when I say 'Anne of", I cannot hear any difference between that and saying  each word separately.

**Comment by thenickcox** [comment] 2015-01-01 17:13
Hey, Chris! Thanks for using this gem. You're right about that discrepancy. I'll take a look today and hopefully get a fix pushed up. 



:: Sent from my mobile device. ::

**Comment by thenickcox** [comment] 2015-01-02 05:49
Closed via c7485cc4b1f3b26df370d2232adf8f2728df875b.

**Closed by thenickcox** 2015-01-02 05:49 UTC

**Comment by thenickcox** [comment] 2015-01-02 05:50
@obromios Just fixed that. Thanks for pointing it out. It was actually a much more glaring bug that didn't have to do with the word 'of', it's that the `strip_punctuation` method just did a Regex match on non-word characters, which includes spaces! I'm surprised that didn't cause bugs before this. But I added a test case for the string 'Anne of' to make sure there aren't regressions there.

**Comment by obromios** [comment] 2015-01-02 06:38
That was quick.

I have pulled it down from github, and it works, thank you.

Chris

**Comment by thenickcox** [comment] 2015-01-02 06:40
@obromios Sure thing. If you run into anyone issues, don't hesitate to file them. There are, after all, a ton of exceptions in English. Also, if you build anything you end up finding interesting, I'd love to see it.

**Comment by obromios** [comment] 2015-01-04 22:37
I am playing with an idea of a Haiku web-app. Given how particular poets
tend to be, I imagine I will be able to provide you lots of feedback if it
goes ahead.

I hope you have a good new year.

Chris

**Comment by thenickcox** [comment] 2015-01-05 22:45
If that's what you're looking to do, @obromios, then you might like my other gem, [haikuable](https://github.com/thenickcox/haikuable), which uses this as a dependency. I built them both to write my own haiku web app, so feel free.

By the way, since you're the only other user of this that I know of, what do you feel about an API for `syllabize` where you can pass in exceptions? Otherwise, you're at the mercy of whatever's in the `exceptions.yml` file, which is always going to be reactive (as opposed to proactive)? So something like:

```ruby
'cooperative negotiations'.count_syllables(exceptions: { cooperative: 4 })
```

**Comment by obromios** [comment] 2015-01-07 04:26
I would be interested to see your haiku web app, what is its url?

I have two more possible exceptions, 'Something' is giving a count of 3,
but I think it should be 2, and 'bones' is giving a count of 2 but I think
it should be 1.  Would you like me to just keep track of these, and at some
time send you my exceptions.yml for you to review?

I think the exceptions option is a good idea, although at this stage,  I
think I will just work with a local version of the exceptions.yml file.

I can see it could be more useful for end users, as it would make it easier
for a developer to allow them to enter their own exceptions. In fact it
could save a lot of argument with end users.  We could have a way of
logging the user found exceptions, and if enough people think a particular
word is wrong, then it is then added to the central exceptions.yml file.

Chris

**Comment by thenickcox** [comment] 2015-01-07 06:23
No, you're right about something and bones. They shouldn't be exceptions. Those are a known issue. I need to consider suffixes, and I [made an issue for that](https://github.com/thenickcox/syllabize/issues/8), and that would work for 'bones', but 'something' is an interesting case. I'll have to think about that more.

I had originally envisioned the exceptions file to contain words like 'naïveté', which are a total edge case that can't realistically (and therefore shouldn't) be considered by the syllable counting algorithm.

As for the haiku app, I never ended up building it! These two gems I thought comprised the most interesting problems to solve.
